<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

/*
  |--------------------------------------------------------------------------
  | Roles
  | 	the Role values are autogenerated values from database
  |--------------------------------------------------------------------------
 */
$config['rbac_roles'] = array(
    'view' => 1,
    'add' => 2,
    'edit' => 3,    
    'admin' => 6,    
);
/*
  |--------------------------------------------------------------------------
  | Controllers -- Task Group
  | 	the Task Group values are autogenerated values from database
  |--------------------------------------------------------------------------
 */
$config['rbac_groups'] = array(
    'Usermanagement' => 4,
    'Example' => 5,
);
/* End of file rbac_itschool.php */
/* Location: ./application/config/rbac_itschool.php */
